name: Publish package at midnight everyday

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
          fetch-depth: 0
      - run: |
          chmod +x ./.github/workflows/check-release.sh
          ./.github/workflows/check-release.sh
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn publish-apps
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
